// BIKEBOUND: procedural 3D courses, checkpoint progression and bike garage.
const $=s=>document.querySelector(s), scene=new THREE.Scene();
scene.background=new THREE.Color('#b9dced');scene.fog=new THREE.Fog('#b9dced',55,190);
const camera=new THREE.PerspectiveCamera(63,innerWidth/innerHeight,.1,400);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xeaf8ff,0x506367,2.1));const sun=new THREE.DirectionalLight(0xfff1d4,3.1);sun.position.set(-20,35,20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const mat=(color,roughness=.7,metalness=0,emissive=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness,emissive});
const M={deck:mat('#29383c'),edge:mat('#c6ff4d',.45,.15,'#263d0a'),metal:mat('#aababc',.32,.75),dark:mat('#11191c',.55,.22),rubber:mat('#101416',.82),red:mat('#fa6650',.46,.15,'#3e0900'),gold:mat('#ffe16a',.32,.4,'#493d04'),safe:mat('#384a4a'),white:mat('#eef7ef')};
const matBike=mat('#c6ff4d',.27,.52,'#172309');
function meshBox(w,h,d,material,x,y,z,parent=scene){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function barBetween(a,b,r,material,parent){const A=new THREE.Vector3(...a),B=new THREE.Vector3(...b),d=B.clone().sub(A),o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,d.length(),9),material);o.position.copy(A.add(B).multiplyScalar(.5));o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());o.castShadow=true;parent.add(o);return o}

const courseNames=['SKYWAY TRIALS','CANYON RUN','FROSTLINE','NEON DOCKS','VOLCANO RIDGE','MOONLIT MESA','JUNGLE DROP','STORM CIRCUIT'];
const courseColors=[0xc6ff4d,0xffaa4d,0x8ee9ff,0xff67a9,0xff6754,0xc99cff,0x82efa9,0xffe078];
const palette=['#c6ff4d','#ff684e','#83dff3','#bd8dff','#ffc84a','#f0f3e9','#ff4f8a','#58e6bf','#4e85ff','#ff8d38','#d9ff54','#ed78ff','#4df0eb','#ef5145','#9bff89','#ffd150','#7aa8ff','#fd91c3','#b4f1ff','#b3ff3d','#fbad70','#9a75ff','#ffe08d','#50c9a2','#ff6980','#8294ff','#daf74c','#ffb6de','#58adff','#c8ffdc','#dd8751','#acdb39','#7aebdc','#ffdc57','#ef75f5','#9aa9b7','#ffa85a','#63e8ff','#ed535c','#a2fa75'];
const bikeNames=['GREEN MACHINE','AFTERBURN','GLACIER','NIGHT SHIFT','GOLD STANDARD','GHOSTLINE','PINK SLIP','MINT CONDITION','BLUE HOUR','SUNSETTER','CITRUS RIP','PURPLE HAZE','DEEP CURRENT','REDLINE','WILD THING','SOLAR FLARE','SKY BREAKER','CANDY CRUSH','ICE PICK','LIMEWIRE','DUST DEVIL','VIOLET RIOT','CHAMPAGNE','TIDAL FORCE','HEART RACER','BLUE STEEL','WASABI','CLOUD NINE','HYPERDRIVE','FAIR PLAY','COPPERHEAD','MOSS BOSS','AQUA JET','LEMON DROP','STARSTRUCK','TITANIUM','FIRESTARTER','TURBO FIN','CRIMSON KING','WILD CARD'];
const bikes=bikeNames.map((name,i)=>({id:'bike-'+i,name,color:palette[i],cost:i===0?0:90+(i-1)*70,grip:1+(i%5)*.025,speed:1+(i%4)*.018}));
const saveData=JSON.parse(localStorage.getItem('bikebound-v2')||'{}');let coins=Number(saveData.coins||0),unlocked=Object.assign(Object.fromEntries(courseNames.map((_,i)=>[i,1])),saveData.unlocked||{}),owned=saveData.owned||[bikes[0].id],selected=saveData.selected||bikes[0].id;
let course=0,level=1,hub=false,started=false,sceneItems=[],surfaces=[],hazards=[],pickups=[],portals=[],checkpointMesh=null,finishZ=-100;
const player={x:0,z:8,y:0,yaw:0,vx:0,vz:0,speed:0,vy:0,grounded:true,fallen:false,done:false};const keys={};

// Bike geometry: each wheel's axle runs across the frame (X axis), like a real bicycle.
const bike=new THREE.Group();scene.add(bike);const rearWheel=new THREE.Group(),frontFork=new THREE.Group();
function buildWheel(group){const tire=new THREE.Mesh(new THREE.TorusGeometry(.56,.115,12,28),M.rubber);tire.rotation.y=Math.PI/2;group.add(tire);const rim=new THREE.Mesh(new THREE.TorusGeometry(.39,.035,8,28),M.metal);rim.rotation.y=Math.PI/2;group.add(rim);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.105,.105,.23,14),M.metal);hub.rotation.z=Math.PI/2;group.add(hub);for(let i=0;i<12;i++){let a=i*Math.PI/6;barBetween([-.012,Math.sin(a)*.38,Math.cos(a)*.38],[.012,Math.sin(a+Math.PI)*.38,Math.cos(a+Math.PI)*.38],.012,M.metal,group)}group.userData.spin=0;}
rearWheel.position.set(0,.59,.91);frontFork.position.set(0,0,-.99);const frontWheel=new THREE.Group();frontWheel.position.set(0,.59,0);frontFork.add(frontWheel);buildWheel(rearWheel);buildWheel(frontWheel);bike.add(rearWheel,frontFork);
const frameParts=[];function tube(a,b,r=.055,material=matBike){frameParts.push(barBetween(a,b,r,material,bike))}
function createFrame(){frameParts.forEach(o=>{bike.remove(o);o.geometry.dispose()});frameParts.length=0;tube([0,.59,.91],[0,1.12,.03]);tube([0,1.12,.03],[0,.59,-.99]);tube([0,.59,.91],[0,.59,-.99]);tube([0,1.12,.03],[0,1.22,-.73]);tube([0,1.22,-.73],[0,.59,-.99]);tube([0,1.12,.03],[0,1.2,.66],.065,M.dark);tube([0,1.22,-.73],[0,1.67,-.99],.045,M.metal);tube([-.4,1.67,-.99],[.4,1.67,-.99],.06,M.dark);meshBox(.5,.09,.25,M.dark,0,1.36,.66,bike);}
createFrame();const torso=meshBox(.32,.57,.27,M.dark,0,1.85,-.08,bike);torso.rotation.x=-.34;const helmet=new THREE.Mesh(new THREE.SphereGeometry(.2,14,12),mat('#f26950',.3));helmet.position.set(0,2.24,-.23);helmet.scale.y=.75;bike.add(helmet);const face=new THREE.Mesh(new THREE.SphereGeometry(.15,12,10),mat('#d9a781'));face.position.set(0,2.08,-.33);bike.add(face);
function setBikeColor(){const b=bikes.find(x=>x.id===selected)||bikes[0];matBike.color.set(b.color);matBike.emissive.set(b.color);matBike.emissiveIntensity=.055;}

function trackSurface(x,y,z,w,len,color=M.deck){const platform=meshBox(w,.48,len,color,x,y-.24,z);sceneItems.push(platform);surfaces.push({x,y,z,w,len,object:platform});sceneItems.push(meshBox(w+.24,.12,len+.12,M.edge,x,y-.48,z));for(const side of [-1,1])sceneItems.push(meshBox(.12,.35,len,M.edge,x+side*(w/2-.16),y-.12,z));}
function cleanCourse(){for(const o of sceneItems){scene.remove(o);o.traverse?.(n=>{if(n.geometry)n.geometry.dispose()})}sceneItems=[];surfaces=[];hazards=[];pickups=[];portals=[];checkpointMesh=null;}
function keep(o){scene.add(o);sceneItems.push(o);return o}
function seeded(seed){let v=seed>>>0;return()=>{v=(v*1664525+1013904223)>>>0;return v/4294967296}}
function movingHazard(x,y,z,index,rng){const mode=index%3;let root=new THREE.Group();root.position.set(x,y,z);keep(root);let body;if(mode===0){body=meshBox(4.6,.34,.5,M.red,0,0,0,root);hazards.push({kind:'slide',object:root,x,y,z,range:2.4,speed:.8+rng()*.7,phase:rng()*6,width:1.4})}else if(mode===1){const pivot=new THREE.Group();root.add(pivot);body=meshBox(.35,3.3,.35,M.red,0,-1.1,0,pivot);meshBox(2.4,.34,.48,M.gold,0,-2.65,0,pivot);hazards.push({kind:'swing',object:pivot,x,y,z,range:.8,speed:1+ rng(),phase:rng()*6,width:1.1})}else{const pivot=new THREE.Group();root.add(pivot);body=meshBox(5,.28,.38,M.red,0,0,0,pivot);hazards.push({kind:'spin',object:pivot,x,y,z,range:1,speed:1.5+rng(),phase:rng()*6,width:1.45})}}
function addCoin(x,y,z){const o=new THREE.Mesh(new THREE.TorusGeometry(.39,.1,9,22),M.gold);o.position.set(x,y+1.15,z);o.rotation.y=Math.PI/2;keep(o);pickups.push({object:o,x,y:y+1.15,z,taken:false})}
function buildHub(){cleanCourse();hub=true;finishZ=-500;trackSurface(0,0,-120,150,170,M.safe);for(let i=0;i<16;i++){let x=-57+(i%8)*16,z=-75-Math.floor(i/8)*57;let r=i%4;const o=r===0?meshBox(10,.7,13,M.deck,x,.35,z):r===1?meshBox(9,.7,9,M.deck,x,.35,z):r===2?meshBox(12,.7,10,M.deck,x,.35,z):meshBox(10,.7,12,M.deck,x,.35,z);sceneItems.push(o);if(r===0)o.rotation.x=-.25;if(r===1)sceneItems.push(meshBox(.35,4,9,M.red,x,.5,z));
 }for(let i=0;i<8;i++){let x=-52+i*15;let portal=new THREE.Mesh(new THREE.TorusGeometry(3,.2,10,32),mat(new THREE.Color(courseColors[i]),.3,.2,0x123333));portal.position.set(x,3,-49);portal.rotation.y=Math.PI/2;keep(portal);keep(meshBox(5,.22,.5,M.edge,x,.12,-49));portals.push({x,z:-49,course:i,object:portal})}
player.x=-7;player.z=-43;player.y=0;player.yaw=0;player.vx=player.vz=player.speed=player.vy=0;player.grounded=true;started=true;toast('FREE RIDE HUB · E AT A GATE TO RIDE');updateUI();}
function loadLevel(c=course,l=level){course=c;level=l;hub=false;cleanCourse();const rng=seeded((c+1)*100003+l*8917);const cc=mat('#'+courseColors[c%8].toString(16).padStart(6,'0'),.55,.1);let cx=0,cy=0;trackSurface(0,0,4,10,24);for(let i=0;i<7;i++){let z=-11-i*15;cx=THREE.MathUtils.clamp(cx+(rng()-.48)*5,-5,5);cy=THREE.MathUtils.clamp(cy+(rng()-.5)*1.4,-1,2.5);const w=7.5+(rng()>.75?2:0),len=17;trackSurface(cx,cy,z,w,len,cc);if(i>0&&i%2===0){const ramp=meshBox(w*.7,.34,4,mat('#667779'),cx,cy+.28,z-5);ramp.rotation.x=-.16;keep(ramp)}const type=(i+c+l)%4;if(type===0||i%2===1)movingHazard(cx,cy+1.12,z-1,i+c+l,rng);for(let k=0;k<2;k++)addCoin(cx+(k?1.2:-1.2),cy,z-5-k*2);}
 // A broad, flat checkpoint tile lies flush on the final section of every level.
const endX=cx,endY=cy;finishZ=-111;trackSurface(endX,endY,finishZ+2,12,12,M.safe);const pad=meshBox(5,.08,5,M.gold,endX,endY+.05,finishZ);keep(pad);checkpointMesh=pad;for(let i=0;i<3;i++)keep(meshBox(4.2,.045,.08,M.edge,endX,endY+.11,finishZ-1.1+i*.9));
player.x=0;player.z=8;player.y=0;player.yaw=0;player.vx=player.vz=player.speed=player.vy=0;player.grounded=true;player.fallen=false;player.done=false;started=true;updateUI();}
function save(){localStorage.setItem('bikebound-v2',JSON.stringify({coins,unlocked,owned,selected}));updateUI()}
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),1800)}
function updateUI(){ $('#coinText').textContent=coins;$('#shopCoin').textContent=coins;$('#runNum').textContent=hub?'HUB':`${course+1}.${String(level).padStart(3,'0')}`;$('#cpText').textContent=`${String((unlocked[course]||1)-1).padStart(3,'0')} / 100`;$('#trackFill').style.width=hub?'100%':`${THREE.MathUtils.clamp((8-player.z)/(8-finishZ)*100,0,100)}%`;$('#speedText').textContent=Math.round(Math.abs(player.speed)*12);}
function makeModal(id,title,subtitle){let old=$('#'+id);if(old)old.remove();let wrap=document.createElement('div');wrap.id=id;wrap.className='modalwrap open';wrap.innerHTML=`<div class="modal"><div class="modalhead"><div><div class="eyebrow">${subtitle}</div><h1>${title}</h1></div><button class="close" data-close>×</button></div><div class="shopmeta" id="${id}Meta"></div><div class="shopgrid" id="${id}Grid"></div></div>`;document.body.appendChild(wrap);wrap.addEventListener('click',e=>{if(e.target===wrap||e.target.closest('[data-close]'))wrap.remove()});return wrap}
function openLevels(){const wrap=makeModal('levelsModal','COURSE SELECT','PROGRESSION · 8 COURSES · 100 LEVELS EACH');wrap.querySelector('.modal').style.width='min(900px,95vw)';let current=0;const fill=()=>{const grid=$('#levelsModalGrid'),best=Number(unlocked[current]||1);grid.style.gridTemplateColumns=innerWidth<650?'repeat(5,minmax(0,1fr))':'repeat(10,minmax(0,1fr))';$('#levelsModalMeta').innerHTML=`<div style="display:flex;gap:8px;flex-wrap:wrap">${courseNames.map((n,i)=>`<button class="button" data-course="${i}" style="${i===current?'border-color:var(--lime);color:var(--lime)':''}">${String(i+1).padStart(2,'0')} · ${n}</button>`).join('')}</div><p>Unlocked through level ${best} · Select any level you have reached.</p>`;grid.innerHTML=Array.from({length:100},(_,i)=>{let n=i+1,open=n<=best;return `<button class="button" data-level="${n}" ${open?'':'disabled'} style="padding:11px 5px;opacity:${open?1:.32};${n===level&&current===course?'border-color:var(--lime)':''}">${String(n).padStart(3,'0')} ${n<best?'✓':''}</button>`}).join('');$('#levelsModalMeta').querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>{current=+b.dataset.course;fill()});grid.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{loadLevel(current,+b.dataset.level);wrap.remove();$('#intro').classList.add('hide')})};fill();}
function openShop(){const wrap=makeModal('garageModal','THE GARAGE','40 RIDES · EARN CREDITS · BUILD YOUR COLLECTION');$('#garageModalMeta').innerHTML=`CREDITS: <span class="coin">◆ ${coins}</span>`;$('#garageModalGrid').innerHTML=bikes.map(b=>{let has=owned.includes(b.id),sel=selected===b.id;return `<div class="item ${sel?'equipped':''}" style="--c:${b.color}"><div class="swatch" style="--c:${b.color}"></div><strong>${b.name}</strong><small>GRIP ${Math.round(b.grip*100)} · TOP SPEED ${Math.round(b.speed*100)}%</small><button class="button" data-bike="${b.id}">${sel?'EQUIPPED':has?'EQUIP':`◆ ${b.cost}`}</button></div>`}).join('');$('#garageModalGrid').querySelectorAll('[data-bike]').forEach(btn=>btn.onclick=()=>{let b=bikes.find(x=>x.id===btn.dataset.bike);if(owned.includes(b.id))selected=b.id;else if(coins>=b.cost){coins-=b.cost;owned.push(b.id);selected=b.id}else{toast('NOT ENOUGH CREDITS');return}setBikeColor();save();openShop()})}
function completeLevel(){if(player.done)return;player.done=true;player.speed=0;player.vx=player.vz=0;coins+=25;unlocked[course]=Math.max(Number(unlocked[course]||1),Math.min(100,level+1));save();toast(`LEVEL ${String(level).padStart(3,'0')} CLEAR · +25 CREDITS`);if(level>=100){setTimeout(buildHub,1000)}else{const panel=document.createElement('div');panel.className='finish open';panel.id='levelClear';panel.innerHTML=`<div><div class="eyebrow">${courseNames[course]} · CHECKPOINT SAVED</div><h2>LEVEL CLEAR</h2><p>Level ${level} checkpoint saved · ◆ 25 credits</p><button class="button" id="nextLevel">NEXT LEVEL ↗</button><button class="button" id="clearLevels">LEVEL SELECT</button></div>`;document.body.appendChild(panel);$('#nextLevel').onclick=()=>{panel.remove();loadLevel(course,level+1)};$('#clearLevels').onclick=()=>{panel.remove();openLevels()}}}
function respawn(){let max=Number(unlocked[course]||1);if(level>max)level=max;loadLevel(course,level);toast('BACK AT CHECKPOINT')}
$('#shopBtn').onclick=openShop;$('#resetBtn').onclick=()=>hub?buildHub():respawn();document.querySelector('.buttons').insertAdjacentHTML('beforeend','<button class="iconbtn" id="levelsBtn">▦ LEVELS</button>');$('#levelsBtn').onclick=openLevels;$('#startBtn').onclick=()=>{$('#intro').classList.add('hide');started=true};$('#againBtn').onclick=()=>{if(hub)buildHub();else loadLevel(course,level)};$('#closeShop').onclick=()=>$('#shop').classList.remove('open');$('#shop').onclick=e=>{if(e.target.id==='shop')e.currentTarget.classList.remove('open')};
addEventListener('keydown',e=>{keys[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Enter'&&!started){started=true;$('#intro').classList.add('hide')}if(e.code==='KeyE'&&!e.repeat&&hub){const p=portals.find(p=>Math.hypot(player.x-p.x,player.z-p.z)<7);if(p){loadLevel(p.course,1);toast(`${courseNames[p.course]} · LEVEL 001`)}}if(e.code==='Escape'){document.querySelectorAll('.modalwrap.open').forEach(x=>x.remove())}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});

// Decorative cloud banks and distant mountain silhouettes.
for(let i=0;i<40;i++){const x=(Math.random()-.5)*170,z=-Math.random()*240-15,h=10+Math.random()*27;const p=new THREE.Mesh(new THREE.ConeGeometry(8+Math.random()*10,h,5),mat(i%4?'#8ca7aa':'#e7f0eb',1));p.position.set(x,h/2-3,z);scene.add(p)}
setBikeColor();loadLevel(0,1);$('#intro').classList.remove('hide');started=false;
let previous=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-previous)/1000,.032);previous=now;const t=now/1000;
for(const h of hazards){if(h.kind==='slide')h.object.position.x=h.x+Math.sin(t*h.speed+h.phase)*h.range;else if(h.kind==='swing')h.object.rotation.x=Math.sin(t*h.speed+h.phase)*.62;else h.object.rotation.y=Math.sin(t*h.speed+h.phase)*1.2;}
for(const p of pickups)if(!p.taken)p.object.rotation.y+=dt*1.6;
if(started&&!player.done&&!document.querySelector('.modalwrap.open')){
 const forward=keys.KeyW||keys.ArrowUp,reverse=keys.KeyS||keys.ArrowDown,left=keys.KeyA||keys.ArrowLeft,right=keys.KeyD||keys.ArrowRight,boost=keys.ShiftLeft||keys.ShiftRight,steer=(right?1:0)-(left?1:0);const spec=bikes.find(b=>b.id===selected)||bikes[0];
 if(forward)player.speed=Math.min(player.speed+(boost?12:7.4)*dt,boost?15*spec.speed:10.2*spec.speed);else player.speed=Math.max(0,player.speed-(reverse?13:2.1)*dt);
 const turnRate=(.45+Math.min(player.speed,10)*.085)*spec.grip;player.yaw-=steer*turnRate*dt;player.vx+=(-Math.sin(player.yaw)*player.speed-player.vx)*Math.min(1,dt*(2.6+player.speed*.16));player.vz+=(-Math.cos(player.yaw)*player.speed-player.vz)*Math.min(1,dt*3.5);player.x+=player.vx*dt;player.z+=player.vz*dt;
 if(keys.Space&&player.grounded){player.vy=6.6+player.speed*.12;player.grounded=false}player.vy-=17*dt;player.y+=player.vy*dt;
 let surface=null,best=1e9;for(const s of surfaces){if(Math.abs(player.x-s.x)<s.w/2+.16&&Math.abs(player.z-s.z)<s.len/2+.2){let score=Math.abs(player.x-s.x)+Math.abs(player.z-s.z)*.025;if(score<best){best=score;surface=s}}}
 if(surface&&player.y<=surface.y+.12&&player.vy<=0){player.y=surface.y;player.vy=0;player.grounded=true}else player.grounded=false;
 if(!hub){for(const h of hazards){const hz=h.kind==='slide'?h.object.position.x:h.x;if(Math.abs(player.z-h.z)<.72&&Math.abs(player.x-hz)<h.width&&player.y<h.y-.48){player.speed*=.22;player.vx+=player.x<hz?-2.2:2.2;toast('OBSTACLE HIT · KEEP YOUR BALANCE')}}
 for(const p of pickups)if(!p.taken&&Math.abs(player.z-p.z)<1&&Math.abs(player.x-p.x)<1.15&&Math.abs(player.y-p.y)<2){p.taken=true;p.object.visible=false;coins+=5;save();toast('+5 CREDITS')}
 if(player.z<=finishZ+1&&Math.abs(player.x-(checkpointMesh?.position.x||0))<5&&player.y<2){completeLevel()}
 }else{if(player.x>63)player.x=-63;if(player.x< -63)player.x=63;if(player.z> -35)player.z=-35;if(player.z< -205)player.z=-205;player.y=0;player.vy=0;player.grounded=true}
 if(!surface&&!hub&&player.y< -12&&!player.fallen){player.fallen=true;player.speed=0;toast('OFF TRACK · RESPAWNING');setTimeout(()=>{player.fallen=false;respawn()},700)}
 if(player.fallen){player.x=0;player.vx=player.vz=0}
}
 bike.position.set(player.x,player.y,player.z);bike.rotation.y=player.yaw;bike.rotation.z+=(((keys.KeyA||keys.ArrowLeft)?1:0)-((keys.KeyD||keys.ArrowRight)?1:0))*.12-bike.rotation.z*Math.min(1,dt*5);bike.rotation.x=THREE.MathUtils.clamp(-player.vy*.012,-.12,.12);rearWheel.rotation.x-=player.speed*dt*1.5;frontWheel.rotation.x-=player.speed*dt*1.5;frontFork.rotation.y=(keys.KeyA||keys.ArrowLeft?1:0)*.24-(keys.KeyD||keys.ArrowRight?1:0)*.24;
const behind=new THREE.Vector3(player.x+Math.sin(player.yaw)*10,player.y+4.4,player.z+Math.cos(player.yaw)*10);camera.position.lerp(behind,Math.min(1,dt*3.4));camera.lookAt(player.x-Math.sin(player.yaw)*7,player.y+1,player.z-Math.cos(player.yaw)*7);updateUI();renderer.render(scene,camera)}requestAnimationFrame(frame);
